codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 5%  # allow 5% drop
        base: auto
        if_ci_failed: error
        if_not_found: success
        informational: false
    patch:
      default:
        target: 50%  # require 50% coverage on new code
        threshold: 20%  # allow 20% variance
        base: auto
        if_ci_failed: error
        if_not_found: success
        informational: true  # make it informational only, won't fail PR

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
